"""可部署的崩塌判据。

论文 Figure 4 用的判据 r̂ / r_test 需要测试集标签，部署时拿不到，这是审稿人最容易
抓住的软肋。本脚本改用一个**全程无标签**的量：

    d = r̂ / π_min

其中 r̂ 是模型在无标签查询批次上预测为少数类的比例，π_min 是训练 prompt 中的少数类
频率。两者在决策时都可用。注意 d 恰好也是 DistPFN 施加给少数类的校正因子
（式 (7) 中 π* = r̂ 时因子为 r̂/π_min），所以"判据"与"被诊断对象"是同一个数：
d→0 既意味着崩塌，也意味着自估计目标的校正退化为恒等变换。

本脚本只做离线诊断，不修改任何实验产物。输出：
  results/detector.json
  paper/tables/detector_gen.tex
"""

from __future__ import annotations

import glob
import json
import os
from collections import defaultdict

import numpy as np
from sklearn.metrics import roc_auc_score

import config

UNITS_DIR = os.path.join(config.RESULTS_DIR, "units")


def load_units() -> list[dict]:
    units = []
    for path in sorted(glob.glob(os.path.join(UNITS_DIR, "*.json"))):
        with open(path, encoding="utf-8") as fh:
            units.append(json.load(fh))
    return units


def build_rows(units, grids=("main12", "extended", "shift")) -> list[dict]:
    rows = []
    for u in units:
        if u.get("grid", "main12") not in grids:
            continue
        mt = u["methods"]
        if "tabpfn" not in mt or "picl" not in mt:
            continue
        minority = u["minority_class"]
        pi_min = float(u["prior_train"][minority])
        r_hat = float(mt["tabpfn"]["predicted_minority_rate"])
        if pi_min <= 0:
            continue
        rows.append(
            {
                "dataset": u["dataset"],
                "seed": u["seed"],
                "setting": u["setting"],
                "version": u["model_version"],
                "d": r_hat / pi_min,
                "r_hat": r_hat,
                "pi_min": pi_min,
                "f1_tabpfn": mt["tabpfn"]["macro_f1"],
                "f1_picl": mt["picl"]["macro_f1"],
                "d_picl": mt["picl"]["macro_f1"] - mt["tabpfn"]["macro_f1"],
                "d_distpfn": (mt.get("distpfn", {}).get("macro_f1", np.nan) - mt["tabpfn"]["macro_f1"]),
            }
        )
    return rows


def evaluate_detector(rows, thresholds=(0.25, 0.50, 0.75)) -> dict:
    """把 d<τ 判为"崩塌、值得校正"，看它能否预测 ΔPICL>0。"""
    d = np.array([r["d"] for r in rows], dtype=float)
    gain = np.array([r["d_picl"] for r in rows], dtype=float)
    y_true = (gain > 0).astype(int)
    out = {"n": len(rows), "n_gain": int(y_true.sum())}

    if len(np.unique(y_true)) == 2:
        # d 越小越可能崩塌，故用 -d 作为正类得分
        out["auc_lowd_predicts_gain"] = float(roc_auc_score(y_true, -d))
    else:
        out["auc_lowd_predicts_gain"] = float("nan")

    out["strata"] = []
    edges = [0.0] + list(thresholds) + [float("inf")]
    for i in range(len(edges) - 1):
        lo, hi = edges[i], edges[i + 1]
        sel = [r for r in rows if lo <= r["d"] < hi]
        if not sel:
            continue
        g = np.array([r["d_picl"] for r in sel], dtype=float)
        gd = np.array([r["d_distpfn"] for r in sel], dtype=float)
        gd = gd[~np.isnan(gd)]
        out["strata"].append(
            {
                "range": f"[{lo:.2f}, {hi:.2f})" if hi != float("inf") else f"[{lo:.2f}, ∞)",
                "n": len(sel),
                "mean_d": float(np.mean([r["d"] for r in sel])),
                "mean_gain_picl": float(g.mean()),
                "frac_positive": float(np.mean(g > 0)),
                "mean_gain_distpfn": float(gd.mean()) if len(gd) else None,
            }
        )
    return out


def write_tex(res: dict, path: str) -> str:
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append(
        "\\caption{A deployable collapse indicator. $d=\\hat r/\\pi_{\\min}$ uses only the "
        "unlabelled query batch ($\\hat r$, the predicted minority rate) and the training "
        "prompt counts ($\\pi_{\\min}$); no test label is read. Rows are strata of $d$; "
        "$\\Delta$PICL is the change in macro-F1 over vanilla TabPFN. The same $d$ is the "
        "factor that a self-estimated target prior applies to the minority class, so the "
        "regime where correction helps most is also the regime where that target "
        "degenerates. Generated by \\texttt{code/detector.py}.}"
    )
    lines.append("\\label{tab:detector_gen}")
    lines.append("\\begin{tabular}{lcrcc}")
    lines.append("\\toprule")
    lines.append("$d$ range & $n$ & mean $d$ & $\\Delta$PICL & frac. $>0$ \\\\")
    lines.append("\\midrule")
    for s in res["strata"]:
        lines.append(
            f"{s['range']} & {s['n']} & {s['mean_d']:.2f} & "
            f"{s['mean_gain_picl']:+.3f} & {s['frac_positive']:.2f} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def main() -> int:
    units = load_units()
    if not units:
        print("没有运行产物。")
        return 1
    rows = build_rows(units)
    res = evaluate_detector(rows)
    res["rows"] = rows

    out_json = os.path.join(config.RESULTS_DIR, "detector.json")
    with open(out_json, "w", encoding="utf-8") as fh:
        json.dump(res, fh, indent=1)

    tex = write_tex(res, os.path.join(config.PAPER_TABLES_DIR, "detector_gen.tex"))

    print(f"单元数 {res['n']}，其中 ΔPICL>0: {res['n_gain']}")
    print(f"AUC(-d → 有增益) = {res['auc_lowd_predicts_gain']:.3f}")
    for s in res["strata"]:
        print(
            f"  d∈{s['range']:>12s} n={s['n']:3d} mean_d={s['mean_d']:.2f} "
            f"ΔPICL={s['mean_gain_picl']:+.3f} frac>0={s['frac_positive']:.2f}"
        )
    print("写出:", out_json)
    print("写出:", tex)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
