"""把 results/summary.json 渲染成 LaTeX 表格，写入 paper/tables/。

产物隔离：表格一律写到 paper/tables/，文件名带 _gen 后缀以区别于 baseline 手写表；
所有数字均来自运行产物，脚本不做任何取整以外的加工。
"""

from __future__ import annotations

import json
import os
import re

import config

LABEL = {
    "tabpfn": "TabPFN",
    "os": "+OS",
    "smote": "+SMOTE",
    "balctx": "BalCtx",
    "thr": "Thr",
    "picl": "PICL",
    "distpfn": "DistPFN",
    "distpfn_t": "DistPFN-T",
    "picl_full": "PICL-Full",
    "picl_oracle": "Oracle",
    "logreg": "LogReg",
    "rf": "RF",
    "xgboost": "XGB",
    "xgboost_w": "XGB-w",
    "catboost": "CatB",
    "catboost_w": "CatB-w",
    "lightgbm": "LGBM",
    "lightgbm_w": "LGBM-w",
}

MAIN_COLUMNS = [
    "tabpfn",
    "os",
    "smote",
    "balctx",
    "thr",
    "picl",
    "distpfn",
    "distpfn_t",
    "picl_oracle",
    "logreg",
    "xgboost_w",
]

SETTING_LABEL = {"natural": "Natural", "ind05": "Induced 5\\%", "ind10": "Induced 10\\%"}
VERSION_LABEL = {"v2": "v2", "v2_5": "v2.5", "v3_5": "v3.5"}


def _fmt_p(p: float) -> str:
    if p != p:
        return "--"
    if p < 1e-3:
        return f"$<10^{{-3}}$"
    return f"${p:.3f}$"


GRID_LABEL = {
    "main12": "twelve-table grid",
    "rare12": "naturally rare panel",
    "extended": "extended grid",
    "shift": "subpopulation-shift protocol",
    "heldout": "held-out tables",
}


def write_mean_table(summary, path, caption_note="", grid="main12"):
    methods = summary["methods"]
    cols = [c for c in MAIN_COLUMNS if c in methods]
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    setting_lbl = SETTING_LABEL.get(summary["setting"], summary["setting"])
    version_lbl = VERSION_LABEL.get(summary["model_version"], summary["model_version"])
    cap = (
        "Mean macro-F1 on the "
        + GRID_LABEL.get(grid, grid)
        + ", {} split, TabPFN {} weights ($n={}$ tables, seeds averaged). "
        "+OS copies minority rows; +SMOTE interpolates; BalCtx downsamples the majority class; "
        "Thr searches a hold-out threshold; PICL, DistPFN and DistPFN-T are closed-form prior "
        "corrections with, respectively, a uniform target, the model's own mean predicted test "
        "distribution, and its temperature-scaled form; Oracle uses the test prevalence and is "
        "not deployable. Generated by \\texttt{{code/export\\_tables.py}} from "
        "\\texttt{{results/}}.{}"
    ).format(setting_lbl, version_lbl, summary["n_datasets"], caption_note)
    lines.append("\\caption{" + cap + "}")
    lines.append("\\label{tab:mean_gen_" + re.sub(r"[^a-zA-Z0-9]", "", f"{grid}{summary['setting']}{version_lbl}") + "}")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("{\\scriptsize")
    lines.append("\\begin{tabular}{l" + "c" * len(cols) + "}")
    lines.append("\\toprule")
    lines.append(" & ".join(["Method"] + [LABEL.get(c, c) for c in cols]) + " \\\\")
    lines.append("\\midrule")
    row = []
    for c in cols:
        row.append(f"{methods[c]['mean']:.3f}")
    lines.append(" & ".join(["mean"] + row) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append("\\end{table}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def write_test_table(summary, path):
    tests = summary["tests"]
    if not tests:
        return None
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append(
        f"\\caption{{One-sided Wilcoxon signed-rank tests on per-dataset macro-F1 means, "
        f"{SETTING_LABEL.get(summary['setting'], summary['setting'])} split, "
        f"TabPFN {VERSION_LABEL.get(summary['model_version'], summary['model_version'])} "
        f"($n={summary['n_datasets']}$). Alternative is ``greater'' for the first method named.}}"
    )
    lines.append(
        "\\label{tab:tests_gen_"
        + re.sub(r"[^a-zA-Z0-9]", "", summary["setting"] + summary["model_version"])
        + "}"
    )
    lines.append("\\begin{tabular}{llccccc}")
    lines.append("\\toprule")
    lines.append("A & B & mean(A) & mean(B) & $\\Delta$ & wins & $p$ \\\\")
    lines.append("\\midrule")
    for key, t in tests.items():
        a, b = key.split("_vs_")
        lines.append(
            f"{LABEL.get(a, a)} & {LABEL.get(b, b)} & {t['mean_a']:.3f} & {t['mean_b']:.3f} & "
            f"{t['mean_diff']:+.3f} & {t['wins_a']}/{t['n']} & {_fmt_p(t['p_one_sided'])} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


PERDATASET_COLUMNS = [
    "tabpfn",
    "os",
    "thr",
    "picl",
    "distpfn",
    "distpfn_t",
    "logreg",
    "xgboost_w",
]


def write_perdataset_table(summary, path):
    """逐数据集的 macro-F1（数据集内先对种子取均值），正文 Table S1。"""
    methods = summary["methods"]
    cols = [c for c in PERDATASET_COLUMNS if c in methods]
    datasets = sorted(methods[cols[0]]["per_dataset"])
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    setting_lbl = SETTING_LABEL.get(summary["setting"], summary["setting"])
    version_lbl = VERSION_LABEL.get(summary["model_version"], summary["model_version"])
    # 花括号与 .format 冲突，这里改用拼接，避免转义
    cap = (
        "\\caption{Per-dataset macro-F1, "
        + setting_lbl
        + " training minority, main twelve-table grid, TabPFN "
        + version_lbl
        + " weights, means over seeds $\\{0,1,2\\}$ ($n="
        + str(summary["n_datasets"])
        + "$ tables). Generated by \\texttt{code/export\\_tables.py} from \\texttt{results/}.}"
    )
    lines.append(cap)
    lines.append("\\label{tab:main12_perdataset}")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("{\\scriptsize")
    lines.append("\\begin{tabular}{l" + "c" * len(cols) + "}")
    lines.append("\\toprule")
    lines.append(" & ".join(["Dataset"] + [LABEL.get(c, c) for c in cols]) + " \\\\")
    lines.append("\\midrule")
    for ds in datasets:
        row = ["\\texttt{" + ds.replace("_", "\\_") + "}"]
        for c in cols:
            row.append(f"{methods[c]['per_dataset'][ds]:.3f}")
        lines.append(" & ".join(row) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append("\\end{table}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


ORACLE_BLOCKS = [
    ("Natural rare", "rare12|natural|v2", config.RARE12),
    ("Induced 5\\%", "main12|ind05|v2", config.MAIN12),
]


def write_oracle_table(data, path):
    """逐数据集对照：均匀目标 (PICL) 与测试 prevalence 目标 (oracle)，正文 Table S3。"""
    lines = []
    lines.append("\\begin{table}[ht]")
    lines.append("\\centering")
    lines.append(
        "\\caption{Macro-F1 when $\\pi^\\star$ is uniform (PICL) or the test prevalence (oracle). "
        "The oracle reads test labels and is not a deployable method. Every cell averages the "
        "three seeds. Generated by \\texttt{code/export\\_tables.py} from \\texttt{results/}.}"
    )
    lines.append("\\label{tab:oracle}")
    lines.append("\\begin{tabular}{lccc}")
    lines.append("\\toprule")
    lines.append("Dataset & TabPFN & Uniform & Oracle \\\\")
    for title, key, order in ORACLE_BLOCKS:
        summary = data["grids"].get(key)
        if not summary:
            continue
        methods = summary["methods"]
        cols = ["tabpfn", "picl", "picl_oracle"]
        have = set(methods["tabpfn"]["per_dataset"])
        datasets = [d for d in order if d in have] or sorted(have)
        lines.append("\\midrule")
        lines.append("\\multicolumn{4}{l}{" + title + "} \\\\")
        for ds in datasets:
            row = ["\\texttt{" + ds.replace("_", "\\_") + "}"]
            for c in cols:
                row.append(f"{methods[c]['per_dataset'][ds]:.3f}")
            lines.append(" & ".join(row) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


RARE_COLUMNS = [
    "tabpfn",
    "os",
    "smote",
    "balctx",
    "thr",
    "picl",
    "logreg",
    "xgboost_w",
]


def write_rare_table(data, path):
    """自然稀有面板逐数据集表（正文 Table S2），rare12|natural|v2。"""
    summary = data["grids"].get("rare12|natural|v2")
    if not summary:
        return None
    methods = summary["methods"]
    cols = [c for c in RARE_COLUMNS if c in methods]
    have = set(methods["tabpfn"]["per_dataset"])
    datasets = [d for d in config.RARE12 if d in have]
    lines = []
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append(
        "\\caption{Natural rare-event panel (minority $\\le 15.5\\%$, no downsampling). "
        "Macro-F1, three seeds. \\texttt{wilt} is kept. Seven rows are related NASA/PROMISE "
        "defect tables. \\texttt{mammography} and \\texttt{mc1} are random 4096-row contexts, "
        "so their single-table numbers carry more sampling variance than the rest. "
        "+SMOTE interpolates in the factorised matrix; +OS copies rows. "
        "Generated by \\texttt{code/export\\_tables.py} from \\texttt{results/}.}"
    )
    lines.append("\\label{tab:rare}")
    lines.append("\\setlength{\\tabcolsep}{3.2pt}")
    lines.append("\\begin{tabular}{l" + "c" * len(cols) + "}")
    lines.append("\\toprule")
    lines.append(" & ".join(["Dataset"] + [LABEL.get(c, c) for c in cols]) + " \\\\")
    lines.append("\\midrule")
    for ds in datasets:
        row = ["\\texttt{" + ds.replace("_", "\\_") + "}"]
        for c in cols:
            row.append(f"{methods[c]['per_dataset'][ds]:.3f}")
        lines.append(" & ".join(row) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def write_collapse_table(rows, path, version):
    """按 ratio = 预测少数类率 / 测试集少数类率 分层。"""
    buckets = [
        ("collapsed", 0.0, 0.25),
        ("partial", 0.25, 0.75),
        ("agreed", 0.75, 1.30),
        ("overshoot", 1.30, 1e9),
    ]
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append(
        "\\caption{Change in macro-F1 over vanilla TabPFN, stratified by "
        "$\\hat r / r_{\\mathrm{test}}$ (predicted minority rate over test-fold minority rate), "
        "TabPFN " + VERSION_LABEL.get(version, version) + ", induced 5\\% setting. "
        "The ratio is computed from the test fold and is an explanation, not a deployable detector.}"
    )
    lines.append("\\label{tab:collapse_gen}")
    lines.append("\\begin{tabular}{lccrcc}")
    lines.append("\\toprule")
    lines.append("Stratum & $n$ & mean ratio & $\\Delta$PICL & $\\Delta$DistPFN & $\\Delta$DistPFN-T \\\\")
    lines.append("\\midrule")
    for name, lo, hi in buckets:
        sel = [r for r in rows if r["ratio"] == r["ratio"] and lo <= r["ratio"] < hi]
        if not sel:
            continue
        import statistics as st

        lines.append(
            f"{name} & {len(sel)} & {st.fmean(r['ratio'] for r in sel):.2f} & "
            f"{st.fmean(r['d_picl'] for r in sel):+.3f} & "
            f"{st.fmean(r['d_distpfn'] for r in sel):+.3f} & "
            f"{st.fmean(r['d_distpfn_t'] for r in sel):+.3f} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def write_version_table(data, path):
    """同一设定下 v2 与 v2.5 的对照：验证结论不绑定某一代权重。"""
    pairs = {}
    for key, s in data["grids"].items():
        grid, setting, version = key.split("|")
        if grid != "main12":
            continue
        pairs.setdefault(setting, {})[version] = s
    if not pairs:
        return None
    versions = ["v2", "v2_5"]
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append(
        "\\caption{Version robustness: mean macro-F1 of each method under the v2 and the v2.5 "
        "classifier weights on the same twelve tables and the same seeds. The ordering of the "
        "methods, not the absolute level, is the object of interest; the v2.5 weights are uniformly "
        "lower here, which is a property of the checkpoint and not of the correction.}"
    )
    lines.append("\\label{tab:version_gen}")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("{\\scriptsize")
    cols = ["tabpfn", "os", "thr", "picl", "distpfn", "distpfn_t", "picl_oracle"]
    lines.append("\\begin{tabular}{ll" + "c" * len(cols) + "}")
    lines.append("\\toprule")
    lines.append(" & ".join(["Split", "Weights"] + [LABEL.get(c, c) for c in cols]) + " \\\\")
    lines.append("\\midrule")
    for setting in [st for st in ["natural", "ind10", "ind05"] if st in pairs]:
        for ver in versions:
            s = pairs[setting].get(ver)
            if not s:
                continue
            row = []
            for c in cols:
                v = s["methods"].get(c)
                row.append(f"{v['mean']:.3f}" if v else "--")
            lines.append(
                " & ".join([SETTING_LABEL.get(setting, setting), VERSION_LABEL.get(ver, ver)] + row) + " \\\\"
            )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append("\\end{table}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def write_shift_table(data, path):
    """天然先验偏移：子群切分下的结果。"""
    rows = []
    for key, s in data["grids"].items():
        grid, setting, version = key.split("|")
        if grid != "shift":
            continue
        rows.append((setting, version, s))
    if not rows:
        return None
    cols = ["tabpfn", "os", "thr", "picl", "distpfn", "distpfn_t", "logreg", "xgboost_w"]
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append(
        "\\caption{Naturally occurring prior shift. No label is resampled: the training rows come "
        "from the subpopulation with the lower minority prevalence and the test rows from the "
        "subpopulation with the higher one, so the shift is a property of the data rather than of "
        "the protocol. Mean macro-F1 over the tables that admit such a split.}"
    )
    lines.append("\\label{tab:shift_gen}")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("{\\scriptsize")
    lines.append("\\begin{tabular}{ll" + "c" * len(cols) + "}")
    lines.append("\\toprule")
    lines.append(" & ".join(["Split", "Weights"] + [LABEL.get(c, c) for c in cols]) + " \\\\")
    lines.append("\\midrule")
    for setting, version, s in sorted(rows):
        row = []
        for c in cols:
            v = s["methods"].get(c)
            row.append(f"{v['mean']:.3f}" if v else "--")
        # setting 里带子群列名（sub_checkingstatus），下划线必须转义后再进 \texttt
        setting_tex = setting.replace("_", "\\_")
        lines.append(
            " & ".join([f"\\texttt{{{setting_tex}}}", VERSION_LABEL.get(version, version)] + row) + " \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append("\\end{table}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def write_detector_table(data, path):
    """按训练留出片保真度分层：可部署判据。"""
    import statistics as st

    rows = []
    for key, det in data.get("detector", {}).items():
        grid, setting, version = key.split("|")
        if grid != "main12" or setting in ("natural",):
            continue
        rows.extend(det)
    if not rows:
        return None
    buckets = [(0.0, 0.34), (0.34, 0.67), (0.67, 1.0), (1.0, 1e9)]
    names = ["$<0.34$", "$0.34$--$0.67$", "$0.67$--$1.0$", "$\\ge 1.0$"]
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append(
        "\\caption{A deployable version of the diagnostic. The fidelity of the prompt prior is "
        "measured on a 20\\% hold-out of the \\emph{training} rows, as the rate at which the model "
        "calls the minority class divided by the true minority rate of that hold-out; no test label "
        "is used. Change in macro-F1 over vanilla TabPFN, pooled over both checkpoints and all "
        "induced settings, stratified by fidelity.}"
    )
    lines.append("\\label{tab:detector_gen}")
    lines.append("\\begin{tabular}{lcrrrr}")
    lines.append("\\toprule")
    lines.append("Fidelity & $n$ & mean & $\\Delta$PICL & $\\Delta$DistPFN & $\\Delta$Thr \\\\")
    lines.append("\\midrule")
    for (lo, hi), name in zip(buckets, names):
        sel = [r for r in rows if lo <= r["fidelity"] < hi]
        if not sel:
            continue
        lines.append(
            f"{name} & {len(sel)} & {st.fmean(r['fidelity'] for r in sel):.2f} & "
            f"{st.fmean(r['d_picl'] for r in sel):+.3f} & "
            f"{st.fmean(r['d_distpfn'] for r in sel):+.3f} & "
            f"{st.fmean(r['d_thr'] for r in sel):+.3f} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def main() -> int:
    path = os.path.join(config.RESULTS_DIR, "summary.json")
    if not os.path.exists(path):
        print("缺少 results/summary.json，先跑 code/analyze.py")
        return 1
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)

    written = []
    # 消融网格（est8/est16/est32 等）不单独出表，只在正文里引用聚合数字
    ablation_prefixes = ("est",)
    for key, summary in data["grids"].items():
        grid, setting, version = key.split("|")
        if grid.startswith(ablation_prefixes):
            continue
        base = f"{grid}_{setting}_{version}"
        written.append(
            write_mean_table(
                summary,
                os.path.join(config.PAPER_TABLES_DIR, f"mean_gen_{base}.tex"),
                grid=grid,
            )
        )
        written.append(
            write_test_table(summary, os.path.join(config.PAPER_TABLES_DIR, f"tests_gen_{base}.tex"))
        )
        # 正文 Table S1：主网格 induced 5% / v2 的逐数据集格子
        if grid == "main12" and setting == "ind05" and version == "v2":
            written.append(
                write_perdataset_table(
                    summary, os.path.join(config.PAPER_TABLES_DIR, "main12_ind05_v2.tex")
                )
            )
        rows = data["collapse"].get(key, [])
        if rows and setting == "ind05":
            written.append(
                write_collapse_table(
                    rows, os.path.join(config.PAPER_TABLES_DIR, f"collapse_gen_{grid}_{version}.tex"), version
                )
            )

    written.append(write_version_table(data, os.path.join(config.PAPER_TABLES_DIR, "version_gen.tex")))
    written.append(write_shift_table(data, os.path.join(config.PAPER_TABLES_DIR, "shift_gen.tex")))
    written.append(write_detector_table(data, os.path.join(config.PAPER_TABLES_DIR, "detector_gen.tex")))
    # 正文 Table S2/S3：rare 面板与 oracle 对照均已统一为 3-seed 产物口径（作者拍板 B）
    written.append(write_rare_table(data, os.path.join(config.PAPER_TABLES_DIR, "rare.tex")))
    written.append(write_oracle_table(data, os.path.join(config.PAPER_TABLES_DIR, "oracle.tex")))

    written = [w for w in written if w]
    for w in written:
        print("写出:", os.path.relpath(w, config.VENUE_ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
